### ISSUE TITLE
MapQ?

### ISSUE THREAD

**Issue by colindaven** [cpockrandt/genmap#1]
Hi,

thanks, interesting package, especially the genome browser capable standard output files.

However, why not use the accepted Mapping Quality that we know and teach, as output by aligners (even if that is theoretically completely different as perhaps not kmer based) ? i.e. 0-250, typically 0-60, instead of introducing another score into genomics ? At least as an option ? 

Thanks,
Colin

**Comment by joshuak94** [comment]
Hey, I think you might be a bit confused. Mappability isn't the same as mapping quality. Mapping quality scores the probability that a read is misplaced.

Mappability has nothing to do with probability, and instead tells you how often a k-mer occurs in the genome.

You could have a 30-mer which is unique, so has a Mappability score of 1. However, if the individual base quality scores in that particular 30-mer are low, then the MAQ would be also low. Likewise, if the base quality scores were high, then the MAQ would be high, while the mappability score hasn't changed.

**Comment by colindaven** [comment]
Nope, not confused - I realize you have a different definition. The issue is - why could mappability not be converted to a more PHRED like score, analogous to those used in many areas of NGS bioinformatics, for example in FASTQ quality scores etc.

PHRED has been very popular and useful, and I'm sure a PHRED like score could be created - even if we are talking direct observation and not likelihoods here (I only have an issue with the scale used here).

The issue is that people have difficulty dealing with low and fractional numbers, I can't imagine my users will be happy with me presenting eg 0.123123 as mappability with 1 being the uppermost score. 

Thanks anyway.

**Comment by joshuak94** [comment]
(I am not the author/creator of the tool) I guess it *could* be converted into a more PHRED-like score. Probably could keep the formula the same, `-10*log(Mappability)`, then you would have a score of 0 would be unique, and the value would increase with decreasing mappability.

Alternatively, you could just output the frequency via the `-fs` or `-fl` options. Then it gives you the actual occurrences of the k-mers, so 1 == unique, 2 if the k-mer occurs twice, etc.

I think the reason @cpockrandt probably didn't convert it to a pre-existing score is because mappability already existed as a pre-existing measurement. It's been used/implemented in various other tools prior to this one, and all of them use either mappability from 0 to 1 or frequencies. So at this point, it's probably a bit too late/confusing to introduce a *different* scoring for mappability, when the score as presented here has existed already for several years.

This is, however, just my take on it. Maybe Chris had a completely different train of thought.

**Comment by cpockrandt** [comment]
Hi Colin,

I can understand that fractionals might not be optimal for some applications. As @joshuak94 pointed out that is why we have the option to just output the frequency values in 8-bit or 16-bit unsigned integers (i.e., the number of occurrences). From there you could translate it into any kind of format (e.g., PHRED like scores).

Since the format of mappability / frequency is already quite common in this context, I don't think we will implement a PHRED like score.
