### ISSUE TITLE
Using bed file selector -S slows down program by magnitudes

### ISSUE THREAD

**Issue by martin-steinegger** [cpockrandt/genmap#14]
Using the bed selector flag of `genmap map -S input.bad` can reduce the speed significantly if the a bed file contains large intervals. Reason for this is that genmap does reused previously computed k-mer mappabilities. Could you please include a flag to reuse the previously detected k-mer information when using `-S`.

**Comment by cpockrandt** [comment]
There's no easy solution to this. I will look into it.

Computing only a subset of the mappability will turn some optimizations off (i.e., avoiding to compute  the mappability of positions with the same k-mer twice). This is definitely much slower since in your case all your sequences are almost identical. In other scenarios turning this optimization on might actually slow down GenMap (if positions have to be located in the FM-index even though the mappability of these positions don't have to be computed eventually). There is no clean way to determine which strategy to choose to achieve the best running time. I will do some benchmarking!

**Comment by martin-steinegger** [comment]
Maybe you could use the information how much of the genome is covered. Reusing previously compute k-mers can be usefull if the bed file selects > 50% of the genome size.

**Comment by cpockrandt** [comment]
Forgot to close this issue.

Was fixed with commit https://github.com/cpockrandt/genmap/commit/8d3a9a15a473971d5c031cbc85b4e676789e1432 and released in v1.2.0
